[package]
name = "include-repo"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]
license = "AGPL-3.0-only"

[dependencies]
proc-macro-hack = "0.4.0"
include-repo-impl = { path = "./include-repo-impl" }
